# cli_def/resources/demo/advanced.toml

[cli]
key = "demo"
help = "Advanced demo CLI"
prompt = "advanced> " # be used when repl mode

# --- template ----------------------------------------

[cli._common]
args = [
  {key="verbose", option="--verbose", is_flag=true}
]

# --- commands ----------------------------------------

[cli.build]
help = "Build target"
inherit_from = ["_common"]
args = [
  {key="target", mult="1", type="str"}
]
entrypoint = "cli_def.demo_handlers:build"

[cli.test]
help = "Run tests"
inherit_from = ["_common"]
args = [
  {key="pattern", mult="?", type="str"}
]
entrypoint = "cli_def.demo_handlers:test"

[cli.deploy]
help = "Deploy application"
args = [
  {key="env", option="--env", mult="?", type="str"},
  {key="force", option="--force", is_flag=true}
]
entrypoint = "cli_def.demo_handlers:deploy"