# cli_def/resource/cli_def.toml

[cli]
"key"="cli-def"
"help"="CliDef Script"

[cli.repl]
"help"= "Interactive Mode"
"args"= [
    {"key"="cli_def_file", "option"="--file", "mult"="?", "type"="str"}
]
"entrypoint"="cli_def.script.main:run_repl"

[cli.demo]
"help"= "Demo"
"args"= [
    {"key"="profile", "mult"="?", "type"="str"}
]
"entrypoint"="cli_def.script.main:run_demo"

[cli.run]
"help"= "Run"
"args"= [
    {"key"="cli_def_file", "mult"="?", "type"="str"}
]
"entrypoint"="cli_def.script.main:run_run"

[cli.dump]
"help"= "Dump cli-def AST"
"args"= [
    {"key"="cli_def_file", "mult"="?", "type"="str"}
]
"entrypoint"="cli_def.script.main:run_dump"
