# cli_def/resource/cli_def.toml

[cli]
key = "cli-def"
help = "CliDef Script"

[cli._early] # for early parsing
args = [
    {key="verbose", option="--verbose", aliases=["-v"], is_flag=true, default=false},
    {key="debug", option="--debug", aliases=["-d"], is_flag=true, default=false},
    {key="backend", option="--backend", type="str", choices=["argparse", "click"]},
]


# --------------------------------------------------------------------------------
# demo command
# --------------------------------------------------------------------------------
[cli.demo]
help = "Demo"
args = [
    {key="profile", mult="?", type="str"}
]
entrypoint = "cli_def.demo.handlers:run_demo"

# --------------------------------------------------------------------------------
# dump command
# --------------------------------------------------------------------------------
[cli.dump]
help = "Dump cli-def AST"
args = [
    {key="cli_def_file", mult="1", type="str"},
    {key="as_help", option="--as-help", is_flag=true},
    {key="show_resolved", option="--resolve", is_flag=true},
    #{key="check_entrypoints", option="--check", is_flag=true, default=false},
]
entrypoint = "cli_def.script.handlers.dump:run_dump"

# --------------------------------------------------------------------------------
# validate command
# --------------------------------------------------------------------------------
[cli.validate]
help = "Validate cli-def AST"
args = [
    {key="cli_def_file", mult="1", type="str"},
]
entrypoint = "cli_def.script.handlers.validate:run_validate"

# --------------------------------------------------------------------------------
# run command
# --------------------------------------------------------------------------------
[cli.run]
help = "Run CLI"
args = [
    {key="cli_def_file", mult="1", type="str"},
    {key="no_ctx_propagate", option="--no-ctx-propagate", is_flag=true, default=false},
]
entrypoint = "cli_def.script.handlers.run:run_run"

# --------------------------------------------------------------------------------
# repl command
# --------------------------------------------------------------------------------
[cli.repl]
help = "Interactive Mode"
args = [
    {key="cli_def_file", option="--file", mult="?", type="str"},
    {key="no_ctx_propagate", option="--no-ctx-propagate", is_flag=true, default=false},
]
entrypoint = "cli_def.script.handlers.repl:run_repl"

# --------------------------------------------------------------------------------
# scan command
# --------------------------------------------------------------------------------
[cli.scan]
help = "Scan late-binding handlers"
entrypoint = "cli_def.script.handlers.scan:run_scan"

[[cli.scan.args]]
key = "package"
mult = "?"
type = "str"

[[cli.scan.args]]
key = "show_early"
option = "--show-early"
is_flag = true
default = false
help = "Show not only late-bindings but early-bindings"

[[cli.scan.args]]
key = "recursive"
option = "--recursive"
aliases = ["-R"]
is_flag = true
default = false
help = "Recursive scan in the specified package"

[[cli.scan.args]]
key = "no_subprocess"
option = "--no_subprocess"
aliases = ["-N"]
is_flag = true
default = false
help = "Package loding will be done in current process instead of subprocess"

[[cli.scan.args]]
key = "check_toml_path"
option = "--check"
mult = "1"
type = "str"
help = "Check whether each handler is bound to the entrypoint or not in TOML"

# --------------------------------------------------------------------------------
# search command
# --------------------------------------------------------------------------------
[cli.search]
help = "Search cli-def TOMLs in specified directory"
entrypoint = "cli_def.script.handlers.search:run_search"

[[cli.search.args]]
key = "directory_to_search"
mult = "1"
type = "str"

[[cli.search.args]]
key = "recursive"
option = "--recursive"
aliases = ["-R"]
is_flag = true
default = false
help = "Recursive search in the specified directory"

[[cli.search.args]]
key = "dump_all"
option = "--dump-all"
aliases = ["-D"]
is_flag = true
default = false
help = "dump each cli-def"
