# cli_def/resource/cli_def.toml

[cli]
key = "cli-def"
help = "CliDef Script"

[cli._early] # for early parsing
args = [
    {key="verbose", option="--verbose", aliases=["-v"], is_flag=true, default=false},
    {key="debug", option="--debug", aliases=["-d"], is_flag=true, default=false},
    {key="backend", option="--backend", type="str", choices=["argparse", "click"], default="argparse", help="Choose backend"},
]

[cli._shared]
args = [
    {key="verify", option="--verify", is_flag=true, default=false},
]

[cli.repl]
help = "Interactive Mode"
args = [
    {key="cli_def_file", option="--file", mult="?", type="str"}
]
#"entrypoint"="cli_def.script.handlers:run_repl" # use decorator binding instead

[cli.demo]
help = "Demo"
args = [
    {key="profile", mult="?", type="str"}
]
#"entrypoint"="cli_def.script.handlers:run_demo" # use decorator binding instead

[cli.run]
help = "Run"
args = [
    {key="cli_def_file", mult="?", type="str"}
]
entrypoint = "cli_def.script.handlers:run_run"

[cli.dump]
help = "Dump cli-def AST"
args = [
    {key="cli_def_file", mult="1", type="str"}
]
entrypoint = "cli_def.script.handlers:run_dump"

[cli.scan]
help = "Scan late-binding handlers"
args = [
    {key="package", mult="?", type="str"},
    {key="show_all", option="--all", is_flag=true, default=false},
    {key="recursive", option="--recursive", aliases=["-R"], is_flag=true, default=false},
    {key="check_toml_path", option="--check", mult="?", type="str"},
]
