# cli_def/demo/profiles/beginner.toml

[cli]
key = "demo"
help = "Beginner demo CLI"
prompt = "beginner> " # be used when repl mode

[cli.echo]
help = "Echo message"
args = [
  {key="message", mult="*", type="str"}
]
entrypoint = "cli_def.demo.handlers:echo"

[cli.greet]
help = "Greet someone"
args = [
  {key="name", mult="?", type="str"},
  {key="upper", option="--upper", aliases=["-U"], is_flag=true}
]
entrypoint = "cli_def.demo.handlers:greet"

[cli.greet-john]
help = "Greet John"
inherit_from = ["greet"]
bind = {"name" = "John"}

[cli.greet-john-loud]
inherit_from = ["greet"]
bind = {name = "John", upper = true}